-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2121
--   at:        2018-03-20 14:24:21 CET
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



CREATE TABLE hostrange (
    host_id    NUMBER NOT NULL,
    hostname   VARCHAR2(30) NOT NULL,
    virus_id   NUMBER NOT NULL
);

ALTER TABLE hostrange ADD CONSTRAINT hostrange_pk PRIMARY KEY ( host_id,
virus_id );

CREATE TABLE protein_function (
    functie_id            NUMBER NOT NULL,
    function              BLOB NOT NULL,
    proteine_protein_id   NUMBER NOT NULL,
    proteine_id           NUMBER NOT NULL
);

ALTER TABLE protein_function ADD CONSTRAINT protein_function_pk PRIMARY KEY ( functie_id );

CREATE TABLE proteine (
    protein_id   NUMBER NOT NULL,
    naam         VARCHAR2(40) NOT NULL,
    virus_id     NUMBER NOT NULL
);

ALTER TABLE proteine ADD CONSTRAINT proteine_pk PRIMARY KEY ( protein_id,
virus_id );

CREATE TABLE virus (
    id              NUMBER NOT NULL,
    naam            VARCHAR2(30) NOT NULL,
    familie         VARCHAR2(40) NOT NULL,
    geslacht        VARCHAR2(20) NOT NULL,
    dna_sequentie   LONG NOT NULL
);

ALTER TABLE virus ADD CONSTRAINT virus_pk PRIMARY KEY ( id );

ALTER TABLE hostrange
    ADD CONSTRAINT hostrange_virus_fk FOREIGN KEY ( virus_id )
        REFERENCES virus ( id );

ALTER TABLE protein_function
    ADD CONSTRAINT protein_function_proteine_fk FOREIGN KEY ( proteine_protein_id,
    proteine_id )
        REFERENCES proteine ( protein_id,
        virus_id );

ALTER TABLE proteine
    ADD CONSTRAINT proteine_virus_fk FOREIGN KEY ( virus_id )
        REFERENCES virus ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
